
```{r, include = FALSE}
leanbuild::set_knitr_image_path()
```

# Overview

There is a growing need for undergraduate students to learn cutting-edge concepts in genomics data science, including performing analysis on the cloud instead of a personal computer. This lesson aims to introduce a mutant detection bioinformatics pipeline based on a publicly available genetic sample of SARS-CoV-2. Students will be introduced to the sequencing revolution, variants, genetic alignments, and essentials of cloud computing prior to the lab activity. During the lesson, students will work hands-on with the point-and-click Galaxy interface on the [AnVIL](https://anvilproject.org/) cloud computing resource to check data, perform an alignment, and visualize their results.

## Activity Context

**Course Audience**  
- Undergraduate biology majors
- Graduate students with less exposure to bioinformatics

**Course Prerequisites**  
- Layman understanding of genetics (understanding of DNA, genes, trait inheritance)
- Some previous exposure to the central dogma of molecular biology

**Class Type**  
- Lab
- Computer-based

**Class Size**  
- 1-50

**Lesson Duration**  
- 20-30 minute pre-lab lecture 
- 3 hour lab for undergraduate students
- 1 hour lab for graduate students
- Additional short lecture modules

**Assessment Type**
Short answer questions at each lab stage
