# Instructor Guide {-}

## Suggested Activity Context {-}

**Course Audience**  

- Undergraduate biology majors
- Graduate students with less exposure to bioinformatics

**Course Prerequisites**  

- Layman understanding of genetics (understanding of DNA, genes, trait inheritance)
- Some previous exposure to the central dogma of molecular biology

**Class Type**  

- Lab
- Computer-based

**Class Size**  

- 1-50

**Lesson Duration**  

- 20-30 minute pre-lab lecture 
- 3 hour lab for undergraduate students
- 1 hour lab for graduate students
- Additional short lecture modules

**Assessment Type**  

- Short answer questions at each lab stage

## Lesson Plan  {-}

| Activity | Undergraduate course | Graduate course | |
| :-- | :-- | :-- | :--|
| Getting started [_Logging into AnVIL_](09-student-guide#set-up), [_Provisioning Galaxy workspace_](09-student-guide#starting-galaxy) | 10-15 minutes | 10-15 minutes | _Provisioning will take 8-10 minutes of waiting_ |
| [Overview lecture](09-student-guide#overview-video) | 15 minutes | 15 minutes | 
| [Exercise 1: Uploading data](09-student-guide#importing-data) | 10 minutes | 5 minutes |
| [Exercise 2: Examining fastQ files](09-student-guide#examining-fastq) | 30 minutes | 10 minutes |
| [Exercise 3: Aligning data](09-student-guide#alignment) | 30 minutes | 10 minutes |
| [Exercise 4: Viewing alignments](09-student-guide#view-alignment) | 30 minutes | 10 minutes |
| [Wrap-up](09-student-guide#wrap-up) | 5-10 minutes | 5 minutes |

## Notes for Instructors {-}

Depending on your needs, you might decide to run this Galaxy activity on a different cloud provider, such as the original [usegalaxy.org](https://usegalaxy.org/). More information about Galaxy is available at [training.galaxyproject.org](https://training.galaxyproject.org).

More Coming soon!

## Getting Credit for Professional Development {-}

We are happy to provide a letter to your supervisor, department head, or dean to indicate you've worked through this content and intend to use it in your class. See the example here.
